[package]
name = "snaprag"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
anyhow = "1.0"
thiserror = "1.0"
pgvector = "0.2"
toml = "0.8"
config = "0.14"
url = "2.4"
tracing = "0.1"
tracing-subscriber = "0.3"
tonic = "0.12"
prost = "0.12"
prost-types = "0.12"
http = "1.0"
sha2 = "0.10"
base64 = "0.21"
hex = "0.4"

[[bin]]
name = "check_config"
path = "src/bin/check_config.rs"

[[bin]]
name = "sync"
path = "src/bin/sync.rs"
