#!/bin/bash
# Optimize AWS EC2 8GB instance for SnapRAG
# This script configures PostgreSQL, system swap, and kernel parameters
# for memory-constrained environments

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "=========================================="
echo "SnapRAG EC2 Memory Optimization (8GB)"
echo "=========================================="
echo ""

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Error: This script must be run as root${NC}"
   echo "Usage: sudo $0"
   exit 1
fi

# ==============================================================================
# 1. Check System Resources
# ==============================================================================

echo -e "${BLUE}Step 1: Checking system resources...${NC}"
echo ""

TOTAL_MEM=$(free -m | awk 'NR==2{print $2}')
TOTAL_SWAP=$(free -m | awk 'NR==3{print $2}')
CPU_CORES=$(nproc)

echo "Total Memory: ${TOTAL_MEM}MB"
echo "Total Swap:   ${TOTAL_SWAP}MB"
echo "CPU Cores:    ${CPU_CORES}"
echo ""

if [ "$TOTAL_MEM" -lt 7000 ]; then
    echo -e "${YELLOW}Warning: Less than 8GB RAM detected. These optimizations are critical.${NC}"
fi

# ==============================================================================
# 2. Configure Swap Space (Critical for 8GB systems)
# ==============================================================================

echo -e "${BLUE}Step 2: Configuring swap space...${NC}"
echo ""

if [ "$TOTAL_SWAP" -lt 4000 ]; then
    echo -e "${YELLOW}Adding 4GB swap file (current swap: ${TOTAL_SWAP}MB)${NC}"
    
    # Create swap file
    if [ ! -f /swapfile ]; then
        echo "Creating 4GB swap file..."
        dd if=/dev/zero of=/swapfile bs=1M count=4096 status=progress
        chmod 600 /swapfile
        mkswap /swapfile
        swapon /swapfile
        
        # Make permanent
        if ! grep -q '/swapfile' /etc/fstab; then
            echo '/swapfile none swap sw 0 0' >> /etc/fstab
        fi
        
        echo -e "${GREEN}✓ Swap file created and enabled${NC}"
    else
        echo -e "${GREEN}✓ Swap file already exists${NC}"
    fi
else
    echo -e "${GREEN}✓ Sufficient swap space available${NC}"
fi

# Configure swappiness (how aggressively to use swap)
echo "Configuring swappiness..."
sysctl vm.swappiness=10  # Use swap only when necessary
echo "vm.swappiness=10" > /etc/sysctl.d/99-snaprag.conf

echo ""

# ==============================================================================
# 3. Configure OOM Killer Protection
# ==============================================================================

echo -e "${BLUE}Step 3: Configuring OOM killer protection...${NC}"
echo ""

# Reduce OOM killer aggressiveness
sysctl vm.oom_kill_allocating_task=0
sysctl vm.panic_on_oom=0
sysctl vm.overcommit_memory=2      # Don't overcommit memory
sysctl vm.overcommit_ratio=80      # Allow 80% RAM + swap overcommit

cat >> /etc/sysctl.d/99-snaprag.conf << 'EOF'
# OOM killer configuration
vm.oom_kill_allocating_task=0
vm.panic_on_oom=0
vm.overcommit_memory=2
vm.overcommit_ratio=80

# Memory management
vm.dirty_ratio=10
vm.dirty_background_ratio=5
vm.vfs_cache_pressure=50
EOF

sysctl -p /etc/sysctl.d/99-snaprag.conf

echo -e "${GREEN}✓ OOM protection configured${NC}"
echo ""

# ==============================================================================
# 4. Optimize PostgreSQL for 8GB RAM
# ==============================================================================

echo -e "${BLUE}Step 4: Optimizing PostgreSQL configuration...${NC}"
echo ""

# Detect PostgreSQL config file
PG_CONF=""
if [ -f "/var/lib/pgsql/15/data/postgresql.conf" ]; then
    PG_CONF="/var/lib/pgsql/15/data/postgresql.conf"
elif [ -f "/var/lib/pgsql/data/postgresql.conf" ]; then
    PG_CONF="/var/lib/pgsql/data/postgresql.conf"
elif [ -f "/etc/postgresql/15/main/postgresql.conf" ]; then
    PG_CONF="/etc/postgresql/15/main/postgresql.conf"
else
    echo -e "${RED}Error: Could not find postgresql.conf${NC}"
    echo "Please manually configure PostgreSQL using the settings below"
    PG_CONF=""
fi

if [ -n "$PG_CONF" ]; then
    echo "Found PostgreSQL config: $PG_CONF"
    
    # Backup original config
    cp "$PG_CONF" "${PG_CONF}.backup.$(date +%Y%m%d_%H%M%S)"
    
    # Apply optimizations for 8GB RAM
    cat >> "$PG_CONF" << 'EOF'

# ========================================
# SnapRAG Optimizations for 8GB EC2
# Generated by optimize_ec2_memory.sh
# ========================================

# Memory Configuration (Conservative for 8GB)
shared_buffers = 1GB                    # 1/8 of RAM (was default 128MB)
effective_cache_size = 4GB              # 1/2 of RAM (for query planner)
maintenance_work_mem = 256MB            # For CREATE INDEX, VACUUM
work_mem = 16MB                         # Per query operation (low to avoid OOM)

# Connection Configuration
max_connections = 50                    # Limit connections (each uses ~5MB)

# Write Optimization
wal_buffers = 16MB
checkpoint_completion_target = 0.9
max_wal_size = 2GB
min_wal_size = 512MB

# Query Performance
random_page_cost = 1.1                  # For SSD storage (default 4.0)
effective_io_concurrency = 200          # For SSD

# Logging (minimal to save disk I/O)
log_min_duration_statement = 1000       # Log queries > 1 second
log_checkpoints = on
log_connections = off                   # Disable to reduce I/O
log_disconnections = off

# Autovacuum (conservative)
autovacuum = on
autovacuum_max_workers = 2              # Limit vacuum workers
autovacuum_naptime = 60s

# Background Writer
bgwriter_delay = 200ms
bgwriter_lru_maxpages = 100
bgwriter_lru_multiplier = 2.0

EOF

    echo -e "${GREEN}✓ PostgreSQL configuration updated${NC}"
    echo ""
    echo -e "${YELLOW}Please restart PostgreSQL:${NC}"
    echo "  sudo systemctl restart postgresql"
else
    echo -e "${YELLOW}Manual PostgreSQL configuration required${NC}"
    echo "Add these settings to postgresql.conf:"
    echo ""
    echo "  shared_buffers = 1GB"
    echo "  effective_cache_size = 4GB"
    echo "  maintenance_work_mem = 256MB"
    echo "  work_mem = 16MB"
    echo "  max_connections = 50"
fi

echo ""

# ==============================================================================
# 5. Create SnapRAG Optimized Config
# ==============================================================================

echo -e "${BLUE}Step 5: Checking SnapRAG configuration...${NC}"
echo ""

if [ -f "config.ec2-8gb.toml" ]; then
    echo -e "${GREEN}✓ Optimized config available: config.ec2-8gb.toml${NC}"
    echo ""
    echo "To use it:"
    echo "  cp config.ec2-8gb.toml config.toml"
    echo "  # Edit config.toml to set your database password"
else
    echo -e "${YELLOW}Warning: config.ec2-8gb.toml not found${NC}"
    echo "Please ensure you're running this from the snaprag directory"
fi

echo ""

# ==============================================================================
# 6. Setup Monitoring
# ==============================================================================

echo -e "${BLUE}Step 6: Setting up monitoring script...${NC}"
echo ""

cat > /usr/local/bin/snaprag-monitor << 'EOF'
#!/bin/bash
# Monitor SnapRAG memory usage

echo "=========================================="
echo "SnapRAG System Monitor"
echo "=========================================="
echo ""

# Memory
echo "Memory Usage:"
free -h
echo ""

# Swap
echo "Swap Usage:"
swapon --show
echo ""

# PostgreSQL
echo "PostgreSQL:"
systemctl status postgresql --no-pager -l | head -5
echo ""

# SnapRAG process
echo "SnapRAG Processes:"
ps aux | grep snaprag | grep -v grep | head -5
echo ""

# Top memory consumers
echo "Top 5 Memory Consumers:"
ps aux --sort=-%mem | head -6
echo ""

# OOM killer events
echo "Recent OOM Events:"
journalctl -k | grep -i "out of memory" | tail -5
EOF

chmod +x /usr/local/bin/snaprag-monitor

echo -e "${GREEN}✓ Monitoring script installed: /usr/local/bin/snaprag-monitor${NC}"
echo ""

# ==============================================================================
# 7. Summary and Next Steps
# ==============================================================================

echo "=========================================="
echo -e "${GREEN}Optimization Complete!${NC}"
echo "=========================================="
echo ""

echo -e "${YELLOW}Next Steps:${NC}"
echo ""
echo "1. Restart PostgreSQL:"
echo "   sudo systemctl restart postgresql"
echo ""
echo "2. Update SnapRAG config:"
echo "   cp config.ec2-8gb.toml config.toml"
echo "   vim config.toml  # Set database password"
echo ""
echo "3. Start with ONE shard only:"
echo "   snaprag sync start --shard 1 --workers 1"
echo ""
echo "4. Monitor memory usage:"
echo "   snaprag-monitor"
echo "   # Or: watch -n 2 free -h"
echo ""
echo "5. After shard 1 completes, add shard 2:"
echo "   # Edit config.toml: shard_ids = [1, 2]"
echo "   snaprag sync start --shard 2 --workers 1"
echo ""

echo -e "${YELLOW}Memory Management Tips:${NC}"
echo ""
echo "• Use --workers 1 (not higher) for 8GB EC2"
echo "• Sync one shard at a time"
echo "• Enable fast sync mode: snaprag fastsync enable"
echo "• Monitor with: snaprag-monitor"
echo "• Check for OOM: journalctl -k | grep -i oom"
echo ""

echo -e "${GREEN}System optimized for 8GB RAM!${NC}"
echo ""


